/* Verilog module instantiation template generated by SCUBA Diamond_2.1_Production (100) */
/* Module Version: 7.1 */
/* Wed Mar 05 09:53:28 2014 */

/* parameterized module instance */
cog0_mem __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
